// Trivia content batch 2 (50 questions: 25 racing / 25 sports), reviewed
// and confirmed by the user before seeding -- see conversation history.
// Kept as its own file per batch, same convention as batch 1. Run via
// `node scripts/seedTriviaBatch2.mjs`.
export const TRIVIA_BATCH_2 = [
  // ── Racing (25) ─────────────────────────────────────────────────────────
  { category: 'racing', difficulty: 'medium', question: 'The Melbourne Cup is run as which type of race?', options: ['Weight-for-age', 'Handicap', 'Set weight', 'Listed'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Cox Plate is run as which type of race?', options: ['Handicap', 'Weight-for-age', 'Set weight', 'Maiden'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'In which year did Michelle Payne become the first female jockey to win the Melbourne Cup?', options: ['2011', '2013', '2015', '2017'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'Michelle Payne won the 2015 Melbourne Cup riding which horse?', options: ['Prince of Penzance', 'Fiorente', 'Almandin', 'Rekindling'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: "Prince of Penzance's 2015 Melbourne Cup win was trained by?", options: ['Chris Waller', 'Darren Weir', 'Gai Waterhouse', 'Peter Moody'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: "Vintage Crop's 1993 Melbourne Cup win was a milestone as the first winner trained where?", options: ['In New Zealand', 'In Europe', 'In Japan', 'In the USA'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Media Puzzle, trained by Dermot Weld, won the Melbourne Cup in which year?', options: ['2000', '2002', '2004', '2006'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: "Cross Counter's 2018 Melbourne Cup win was the first for which major international racing operation?", options: ['Coolmore', 'Godolphin', 'Juddmonte', 'WinStar'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Which horse won the 2020 Melbourne Cup, run without a crowd due to COVID-19?', options: ['Twilight Payment', 'Verry Elleegant', 'Gold Trip', 'Vow And Declare'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: 'Verry Elleegant, trained by Chris Waller, won the Melbourne Cup in which year?', options: ['2019', '2020', '2021', '2022'], correct_option: 2 },
  { category: 'racing', difficulty: 'easy', question: 'In a "handicap" race, horses carry different weights mainly to...?', options: ['slow down the fastest horses only', "equalise each horse's winning chances", 'meet minimum safety weight rules', "reflect the jockey's experience"], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'In a "weight-for-age" race, weights are assigned based on...?', options: ['recent prizemoney won', 'age, sex, distance and time of year', 'barrier draw position', "trainer's win rate"], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'A "trifecta" bet requires picking...?', options: ['the winner only', 'the first two in either order', 'the first three placegetters in exact order', 'any placegetter in the race'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'A "quinella" bet requires picking...?', options: ['the first two placegetters, in either order', 'the winner only', 'four placegetters', 'the first three in exact order'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: 'A "photo finish" camera is used to...?', options: ['fine jockeys for whip use', 'determine the result of a very close finish', "check a horse's identity", 'time the barrier draw'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'Barrier (starting gate) positions for a race are determined by a...?', options: ['coin toss', 'barrier draw', "trainer's request only", 'weight ranking'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'In racing, a horse described as "spelling" is...?', options: ['racing overseas', 'resting, not currently in work', 'about to be retired', 'recovering from surgery'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: "A young male horse that hasn't been gelded is called a...?", options: ['Colt', 'Filly', 'Gelding', 'Foal'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: 'A young female horse is called a...?', options: ['Colt', 'Filly', 'Mare', 'Dam'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'The notorious 1984 "Fine Cotton" ring-in scandal took place at which racecourse?', options: ['Flemington', 'Eagle Farm', 'Randwick', 'Caulfield'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: "Phar Lap's final race win came in Mexico in the...?", options: ['Santa Anita Handicap', 'Agua Caliente Handicap', 'Del Mar Futurity', 'Hollywood Gold Cup'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: "Makybe Diva's three Melbourne Cup wins (2003–05) were all ridden by which jockey?", options: ['Damien Oliver', 'Glen Boss', 'Craig Williams', 'Hugh Bowman'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: "Sydney's rich sprint race The Everest is unique because entry is via...?", options: ['open nomination', 'purchased/owned "slots"', 'trainer invitation only', 'a qualifying series'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Golden Eagle, a rich race for four-year-olds and up, is run at which racecourse?', options: ['Randwick', 'Flemington', 'Rosehill Gardens', 'Caulfield'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'The All Star Mile, decided partly by public vote, is run at which racecourse?', options: ['Flemington', 'Caulfield', 'Moonee Valley', 'Sandown'], correct_option: 0 },

  // ── Sports (25) ─────────────────────────────────────────────────────────
  { category: 'sports', difficulty: 'medium', question: 'The modern Olympic Games were revived in which year?', options: ['1886', '1896', '1906', '1916'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The first modern Olympic Games were held in which city?', options: ['Rome', 'Paris', 'Athens', 'London'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'The Olympic motto "Citius, Altius, Fortius" translates to?', options: ['Faster, Higher, Stronger', 'Honour, Glory, Victory', 'Together, Forever, Strong', 'Peace, Sport, Unity'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: 'The AFL Grand Final is traditionally played at which venue?', options: ['SCG', 'MCG', 'Marvel Stadium', 'Adelaide Oval'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The NRL Grand Final is traditionally played in which city?', options: ['Melbourne', 'Brisbane', 'Sydney', 'Canberra'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'Cricket Test matches are traditionally played over up to how many days?', options: ['3', '4', '5', '7'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'In cricket, being out "for a duck" means the batter scored?', options: ['One run', 'Zero runs', 'A century', "It's not a real term"], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'A "century" in cricket refers to a batter scoring?', options: ['50 runs', '100 runs', '100 balls faced', '10 wickets'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Basketball was invented by which person?', options: ['James Naismith', 'Walter Camp', 'Abner Doubleday', 'William Webb Ellis'], correct_option: 0 },
  { category: 'sports', difficulty: 'medium', question: 'Golf is widely credited as having originated in which country?', options: ['England', 'Ireland', 'Scotland', 'Netherlands'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'The Rugby (union) World Cup is held how often?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'In a men\'s Grand Slam tennis final (best of five sets), a player must win how many sets?', options: ['2', '3', '4', '5'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: "In a women's Grand Slam tennis final (best of three sets), a player must win how many sets?", options: ['1', '2', '3', '4'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Golf\'s "grand slam" refers to winning all four of a sport\'s...?', options: ['national opens', 'major championships', 'world rankings events', 'team cups'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Table tennis is widely believed to have originated in which country?', options: ['China', 'Japan', 'England', 'USA'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'The biathlon combines cross-country skiing with which other discipline?', options: ['Archery', 'Rifle shooting', 'Fencing', 'Ice skating'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'A "century break" in snooker means scoring at least how many points in one visit?', options: ['50', '75', '100', '147'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'Rod Laver Arena, in Melbourne, is the main stadium for which tennis tournament?', options: ['The Australian Open', 'Wimbledon', 'The US Open', 'The French Open'], correct_option: 0 },
  { category: 'sports', difficulty: 'medium', question: 'Professional cycling\'s three "Grand Tours" are the Tour de France, the Giro d\'Italia, and the...?', options: ['Vuelta a España', 'Tour Down Under', 'Paris–Roubaix', 'Tour de Suisse'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: 'Australia co-hosted the 2023 FIFA Women\'s World Cup with which country?', options: ['Japan', 'New Zealand', 'Canada', 'England'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The AFL Women\'s (AFLW) competition began in which year?', options: ['2015', '2017', '2019', '2021'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'Athletics events like the javelin, discus, shot put and hammer fall under which overall sport?', options: ['Decathlon only', 'Track and field', 'Pentathlon', 'Field games'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The Melbourne Cricket Ground is affectionately nicknamed?', options: ['"The Shed"', '"The G"', '"The Fortress"', '"The Colosseum"'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'In rugby league, a penalty goal is worth how many points?', options: ['1', '2', '3', '4'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'In rugby union, a penalty goal is worth how many points?', options: ['1', '2', '3', '5'], correct_option: 2 },
];
