// Trivia content batch 3 (50 questions: 25 racing / 25 sports), reviewed
// and confirmed by the user before seeding -- see conversation history.
export const TRIVIA_BATCH_3 = [
  // ── Racing (25) ─────────────────────────────────────────────────────────
  { category: 'racing', difficulty: 'medium', question: 'Southern Hemisphere racehorses (e.g. in Australia) officially turn a year older on which date?', options: ['January 1', 'July 1', 'August 1', 'October 1'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'Northern Hemisphere racehorses officially turn a year older on which date?', options: ['January 1', 'April 1', 'June 1', 'December 25'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: 'Melbourne Cup Day is a public holiday in which Australian state?', options: ['New South Wales', 'Victoria', 'Queensland', 'South Australia'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'Melbourne Cup Day always falls on which day of the week?', options: ['Monday', 'Tuesday', 'Thursday', 'Saturday'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Oaks Day, part of the Melbourne Spring Racing Carnival, is informally known as?', options: ["Ladies' Day", 'Family Day', 'Fashion Day', 'Champions Day'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: 'A "Listed" race sits at which level of the racing grading system?', options: ['Above Group 1', 'Just below Group races', 'Equivalent to a maiden', 'Only for two-year-olds'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A horse winning very easily by a big margin is often described as?', options: ['Bolting in', 'Boxed in', 'Hanging', 'Sitting parked'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: '"First-up" describes a horse racing?', options: ['In its first-ever start', 'For the first time since a spell', 'In a Group 1 for the first time', 'Interstate for the first time'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A "roughie" in racing slang refers to?', options: ['A heavily backed favourite', 'A long-priced outsider', 'A horse that just won', 'A first starter'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'The "favourite" in a race is the horse with the?', options: ['Longest odds', 'Shortest odds', 'Best barrier', 'Heaviest weight'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'An "odds-on" favourite has odds shorter than?', options: ['Even money', '5/1', '10/1', '100/1'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: 'An "each-way" bet combines which two bet types?', options: ['Win and quinella', 'Win and place', 'Place and trifecta', 'Exacta and quinella'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'A "protest" after a race is typically lodged over?', options: ['Prizemoney disputes', 'Interference during the race', 'Jockey silks colour', 'Barrier allocation'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'If a protest is upheld, the winning horse can be?', options: ['Given extra prizemoney', 'Relegated/demoted in the placings', 'Disqualified from future races', 'Re-weighed'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Which horse handed the legendary US champion Man o’ War the only loss of his career?', options: ['Upset', 'Exterminator', 'Sir Barton', 'Whisk Broom II'], correct_option: 0 },
  { category: 'racing', difficulty: 'hard', question: 'Seattle Slew, the 1977 US Triple Crown winner, is notable as the only Triple Crown winner to also have been?', options: ['Ridden by an apprentice jockey', 'Unbeaten going into the Triple Crown', 'Trained by a woman', 'Sold before racing'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Affirmed won the US Triple Crown in which year, narrowly beating rival Alydar in all three legs?', options: ['1973', '1978', '1983', '1988'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Which horse ended a 37-year US Triple Crown drought by winning in 2015?', options: ['California Chrome', 'American Pharoah', 'Justify', 'Justin Case'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Which horse won the US Triple Crown in 2018?', options: ['Justify', 'Authentic', 'Medina Spirit', 'Country House'], correct_option: 0 },
  { category: 'racing', difficulty: 'hard', question: "Champion European filly Enable won the Prix de l'Arc de Triomphe in which two consecutive years?", options: ['2015 & 2016', '2017 & 2018', '2019 & 2020', '2016 & 2017'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: "The Prix de l'Arc de Triomphe is run at which Paris racecourse?", options: ['Longchamp', 'Chantilly', 'Saint-Cloud', 'Deauville'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: 'Royal Ascot, the prestigious British meeting attended by the monarch, is held at which racecourse?', options: ['Epsom', 'Ascot', 'Newmarket', 'Goodwood'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: "The Breeders' Cup, US racing's end-of-season championship day, was first held in which year?", options: ['1978', '1984', '1990', '1996'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: "Seabiscuit's famous 1938 match race rival was which horse?", options: ['War Admiral', 'Whirlaway', 'Citation', 'Count Fleet'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: 'Jockey Jamie Kah rose to prominence primarily racing in which Australian state?', options: ['New South Wales', 'Victoria', 'Queensland', 'Western Australia'], correct_option: 1 },

  // ── Sports (25) ─────────────────────────────────────────────────────────
  { category: 'sports', difficulty: 'medium', question: 'Pelé won the FIFA World Cup with Brazil how many times?', options: ['1', '2', '3', '4'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'The first FIFA World Cup, in 1930, was held in which country?', options: ['Brazil', 'Uruguay', 'Italy', 'France'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Which country has won the most FIFA Men\'s World Cup titles?', options: ['Germany', 'Argentina', 'Brazil', 'Italy'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'Sprint legend Usain Bolt represented which country?', options: ['Trinidad and Tobago', 'Jamaica', 'Barbados', 'USA'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Usain Bolt holds world records in which two individual sprint events?', options: ['100m and 200m', '200m and 400m', '100m and 400m', '60m and 100m'], correct_option: 0 },
  { category: 'sports', difficulty: 'medium', question: 'Michael Jordan won how many NBA championships with the Chicago Bulls?', options: ['4', '5', '6', '7'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'Serena Williams holds the Open Era record of how many Grand Slam singles titles?', options: ['19', '21', '23', '25'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'An Ashes cricket series is traditionally contested over how many Test matches?', options: ['3', '4', '5', '6'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'In One Day International (ODI) cricket, each side bats for how many overs?', options: ['20', '40', '50', '60'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'In T20 cricket, each side bats for how many overs?', options: ['10', '20', '30', '40'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The Melbourne Cricket Ground has a capacity of over how many people?', options: ['50,000', '75,000', '100,000', '150,000'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'Australian swimmer Ian Thorpe was nicknamed?', options: ['"The Rocket"', '"Thorpedo"', '"The Shark"', '"Flipper"'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'Cathy Freeman famously won 400m gold at which Olympic Games?', options: ['Atlanta 1996', 'Sydney 2000', 'Athens 2004', 'Beijing 2008'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Dawn Fraser won Olympic 100m freestyle gold at how many consecutive Olympics?', options: ['2', '3', '4', '5'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The Australian Open tennis tournament is held in which month?', options: ['November', 'January', 'March', 'June'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: "Rugby league's State of Origin series is contested over how many games?", options: ['2', '3', '4', '5'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The Australian Grand Prix (Formula 1) is held at which circuit?', options: ['Phillip Island', 'Albert Park', 'Bathurst', 'Eastern Creek'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: "Golf's Masters Tournament is held annually at which course?", options: ['St Andrews', 'Pebble Beach', 'Augusta National', 'Pinehurst'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: "The winner of golf's Masters Tournament is awarded a?", options: ['Silver cup', 'Green jacket', 'Gold medal', 'Claret Jug'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: "Netball Australia's national team is nicknamed the?", options: ['Opals', 'Diamonds', 'Swifts', 'Firebirds'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: "Australia's national men's basketball team is nicknamed the?", options: ['Boomers', 'Opals', 'Wallabies', 'Kookaburras'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: "Australia's national rugby union team is nicknamed the?", options: ['Kangaroos', 'Wallabies', 'Waratahs', 'Reds'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: "Australia's national rugby league team is nicknamed the?", options: ['Wallabies', 'Kangaroos', 'Maroons', 'Blues'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: "Australia's men's cricket team is closely associated with the iconic?", options: ['Golden helmet', 'Baggy green cap', 'Silver fern', 'Green blazer'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The NBA is a professional league primarily based in which country?', options: ['Canada', 'UK', 'USA', 'Australia'], correct_option: 2 },
];
