// Trivia content batch 1 (50 questions: 25 racing / 25 sports), reviewed
// and confirmed by the user before seeding -- see conversation history.
// Kept as its own file per batch (rather than appending to
// gamesTriviaSeed.js) so each batch's provenance/review status stays
// traceable. Run via `node scripts/seedTriviaBatch1.mjs`.
export const TRIVIA_BATCH_1 = [
  // ── Racing (25) ─────────────────────────────────────────────────────────
  { category: 'racing', difficulty: 'easy', question: 'The Melbourne Cup is nicknamed "the race that..."', options: ['stops a nation', 'never sleeps', 'writes history', 'crowns kings'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: 'In what year was the first Melbourne Cup run?', options: ['1851', '1861', '1871', '1901'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Which horse won the first two Melbourne Cups, in 1861 and 1862?', options: ['Archer', 'Carbine', 'Phar Lap', 'Rising Fast'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: 'Which trainer holds the record for the most Melbourne Cup wins (12), earning the nickname "Cups King"?', options: ['Colin Hayes', 'Bart Cummings', 'Gai Waterhouse', 'Lee Freedman'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Champion racehorse Phar Lap died in which country in 1932?', options: ['Australia', 'New Zealand', 'United States', 'England'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'Kingston Town famously won how many consecutive Cox Plates (1980–82)?', options: ['Two', 'Three', 'Four', 'Five'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Might And Power won both the Cox Plate and the Melbourne Cup in the same year. Which year?', options: ['1995', '1997', '1999', '2001'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Cox Plate is run over what distance?', options: ['1600m', '2000m', '2040m', '2400m'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'The Doncaster Mile is run at which racecourse?', options: ['Flemington', 'Randwick', 'Caulfield', 'Eagle Farm'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'The Golden Slipper Stakes is run over what distance?', options: ['1000m', '1200m', '1400m', '1600m'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Flemington Racecourse sits on the banks of which river?', options: ['Yarra River', 'Maribyrnong River', 'Werribee River', 'Merri Creek'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'In racing bets, a "quaddie" requires picking the winners of how many nominated races?', options: ['Two', 'Three', 'Four', 'Six'], correct_option: 2 },
  { category: 'racing', difficulty: 'easy', question: '"Group 1" races represent which level of race grading?', options: ['Lowest grade', 'Mid grade', 'Highest grade', 'Trial-only grade'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'After a race, jockeys must be officially...', options: ['interviewed', 'weighed in', 'fingerprinted', 're-registered'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A "dead-heat" occurs when...', options: ['a horse is scratched late', 'two or more horses finish in a tie', 'a race is abandoned', 'a jockey is disqualified'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Running "on the rails" means a horse is running...', options: ['at the very back', 'wide of the field', 'along the inside of the track', 'alongside the leader only'], correct_option: 2 },
  { category: 'racing', difficulty: 'easy', question: 'Champion mare Winx was trained by which trainer?', options: ['Chris Waller', 'Gai Waterhouse', 'Peter Moody', 'Anthony Cummings'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: 'Black Caviar was trained by which trainer?', options: ['Chris Waller', 'Peter Moody', 'David Hayes', 'Darren Weir'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'In Australian racing/betting, what does "TAB" stand for?', options: ['Track and Betting', 'Totalisator Agency Board', 'The Australian Bookmaker', 'Total Assured Bet'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Jockey Damien Oliver rode which horse to victory in the 2013 Melbourne Cup?', options: ['Green Moon', 'Dunaden', 'Fiorente', 'Almandin'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: 'Champion British racehorse Frankel retired unbeaten after how many starts?', options: ['10', '14', '18', '21'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Secretariat won the US Triple Crown in which year?', options: ['1969', '1973', '1977', '1981'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Kentucky Derby is run at which racecourse?', options: ['Belmont Park', 'Santa Anita', 'Churchill Downs', 'Pimlico'], correct_option: 2 },
  { category: 'racing', difficulty: 'hard', question: 'The English Derby is run at which racecourse?', options: ['Ascot', 'Epsom Downs', 'Newmarket', 'Goodwood'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Red Rum famously won the Grand National how many times?', options: ['Two', 'Three', 'Four', 'Five'], correct_option: 1 },

  // ── Sports (25) ─────────────────────────────────────────────────────────
  { category: 'sports', difficulty: 'easy', question: 'Wimbledon is played in which city?', options: ['Paris', 'London', 'Melbourne', 'New York'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Wimbledon is the only tennis Grand Slam played on which surface?', options: ['Clay', 'Hard court', 'Grass', 'Synthetic'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'The Olympic flag features how many interlocking rings?', options: ['4', '5', '6', '7'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The sport of cricket is widely considered to have originated in which country?', options: ['Australia', 'India', 'England', 'South Africa'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'The NBA shot clock gives a team how many seconds to attempt a shot?', options: ['14', '18', '24', '30'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'Australian Rules Football is widely considered to have originated in which city?', options: ['Sydney', 'Melbourne', 'Adelaide', 'Perth'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The Boxing Day Test cricket match is traditionally played at which venue?', options: ['SCG', 'MCG', 'Gabba', 'Adelaide Oval'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'Rugby union teams have how many players per side?', options: ['13', '14', '15', '16'], correct_option: 2 },
  { category: 'sports', difficulty: 'hard', question: 'The term "hat-trick" is widely said to have originated in which sport?', options: ['Cricket', 'Ice hockey', 'Soccer', 'Rugby'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: 'The FIFA World Cup is held how often?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'Which sport uses the term "love" to mean a zero score?', options: ['Golf', 'Tennis', 'Cricket', 'Squash'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'In AFL, a "goal" is worth how many points?', options: ['1', '3', '6', '7'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'A standard Olympic swimming pool is how many metres long?', options: ['25m', '50m', '100m', '200m'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The Commonwealth Games are held how often?', options: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 6 years'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'In netball, how many players are on court per team?', options: ['5', '6', '7', '9'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'In golf, scoring two strokes under par on a hole is called a(n)?', options: ['Birdie', 'Eagle', 'Albatross', 'Bogey'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'A standard NBA basketball game has how many quarters?', options: ['2', '3', '4', '5'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'The three disciplines of an Ironman triathlon are swim, cycle, and...?', options: ['Row', 'Run', 'Ski', 'Climb'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The Super Bowl is the championship game of which league?', options: ['NBA', 'NHL', 'NFL', 'MLB'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: 'In ice hockey, how many players per team are on the ice at once (including the goalie)?', options: ['5', '6', '7', '8'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'In darts, players traditionally start a leg at 501 and count down to?', options: ['1', 'Zero exactly, via checkout', '50', '100'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The official marathon distance is approximately how many kilometres?', options: ['32km', '37km', '42km', '50km'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'A cricket team fields how many players?', options: ['9', '10', '11', '12'], correct_option: 2 },
  { category: 'sports', difficulty: 'hard', question: 'Olympic "gold" medals are actually made mostly of which metal?', options: ['Bronze', 'Silver', 'Solid gold', 'Nickel'], correct_option: 1 },
  { category: 'sports', difficulty: 'hard', question: 'The Ashes urn, awarded to the winning cricket team, is traditionally said to be made of?', options: ['Porcelain', 'Terracotta', 'Bronze', 'Glass'], correct_option: 1 },
];
