// Trivia content batch 5 (50 questions: 25 racing / 25 sports), reviewed
// and confirmed by the user before seeding -- see conversation history.
// Final batch: brings the pool to 290 questions total, stopped here per
// the user's explicit call to prioritise quality/confidence over hitting
// the top of the original 300-500 range.
export const TRIVIA_BATCH_5 = [
  // ── Racing (25) ─────────────────────────────────────────────────────────
  { category: 'racing', difficulty: 'easy', question: "A horse's father, in its pedigree, is called the?", options: ['Sire', 'Dam', 'Stud', 'Line'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: "A horse's mother, in its pedigree, is called the?", options: ['Sire', 'Dam', 'Foal', 'Stud'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A "stallion" is a male horse used primarily for?', options: ['Racing only', 'Breeding', 'Trials', 'Jumps racing'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A "broodmare" is a female horse used primarily for?', options: ['Racing only', 'Breeding', 'Trials', 'Barrier work'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A horse that has been castrated is called a?', options: ['Colt', 'Gelding', 'Filly', 'Foal'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'Racehorse auctions selling horses aged around one year old are known as?', options: ['Yearling sales', 'Foal sales', 'Maiden sales', 'Breeze-up only'], correct_option: 0 },
  { category: 'racing', difficulty: 'easy', question: "Another word for a jockey's racing colours is?", options: ['Blazon', 'Silks', 'Livery', 'Crest'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'One mile, a distance still referenced in racing, is approximately how many metres?', options: ['1200m', '1609m', '1800m', '2000m'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'The Melbourne Cup Carnival takes place during which Australian season?', options: ['Summer', 'Autumn', 'Winter', 'Spring'], correct_option: 3 },
  { category: 'racing', difficulty: 'medium', question: 'The Golden Slipper Stakes is run during which Australian season?', options: ['Summer', 'Autumn', 'Winter', 'Spring'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Dubai World Cup, one of the world\'s richest races, is held at which racecourse?', options: ['Meydan', 'Nad Al Sheba Old', 'Jebel Ali', 'Sharjah'], correct_option: 0 },
  { category: 'racing', difficulty: 'medium', question: "Hong Kong's major Group 1 races, including the Hong Kong Cup, are run at which racecourse?", options: ['Happy Valley', 'Sha Tin', 'Kowloon Park', 'Victoria Park'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Japan Cup is run at which racecourse?', options: ['Nakayama', 'Hanshin', 'Tokyo Racecourse', 'Kyoto'], correct_option: 2 },
  { category: 'racing', difficulty: 'medium', question: "The Breeders' Cup Classic, the marquee US race, is traditionally run on which track surface?", options: ['Turf', 'Dirt', 'Synthetic', 'Sand'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: "The Grand National, famous for Red Rum's three wins, is run over which type of racing?", options: ['Flat racing', 'Steeplechase (jumps)', 'Harness racing', 'Barrier trials'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Cheltenham Festival, a major jumps racing carnival, is held in which country?', options: ['Ireland', 'England', 'France', 'Wales'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'The Cheltenham Gold Cup is the most prestigious event in which discipline?', options: ['Flat racing', 'Harness racing', 'Steeplechase', 'Barrier trials'], correct_option: 2 },
  { category: 'racing', difficulty: 'hard', question: 'So You Think, first trained by Bart Cummings, won back-to-back Cox Plates in which two years?', options: ['2007 & 2008', '2009 & 2010', '2011 & 2012', '2013 & 2014'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Northerly, a champion WA-bred stayer, won the Cox Plate in which two years?', options: ['1999 & 2000', '2001 & 2002', '2003 & 2004', '2005 & 2006'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Almandin won the Melbourne Cup in which year?', options: ['2014', '2016', '2018', '2020'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Efficient won the Melbourne Cup in which year?', options: ['2005', '2007', '2009', '2011'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Shocking won the Melbourne Cup in which year?', options: ['2007', '2009', '2011', '2013'], correct_option: 1 },
  { category: 'racing', difficulty: 'hard', question: 'Green Moon won the Melbourne Cup in which year?', options: ['2010', '2012', '2014', '2016'], correct_option: 1 },
  { category: 'racing', difficulty: 'medium', question: 'A horse\'s "agistment" refers to?', options: ['Its official rating', 'Paid grazing/care on another property', 'A type of race', 'A veterinary check'], correct_option: 1 },
  { category: 'racing', difficulty: 'easy', question: 'A "yearling" is a horse of approximately what age?', options: ['6 months', '1 year', '2 years', '3 years'], correct_option: 1 },

  // ── Sports (25) ─────────────────────────────────────────────────────────
  { category: 'sports', difficulty: 'easy', question: '"AFL" stands for?', options: ['Australian Football League', 'Athletic Federation League', 'Australian Field League', 'All Football League'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: '"NRL" stands for?', options: ['National Rugby League', 'New Rugby League', 'National Referees League', 'North Rugby League'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: "The Olympic rings represent the world's five inhabited?", options: ['Oceans', 'Continents', 'Time zones', 'Hemispheres'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The Paralympic Games are held?', options: ['A year before the Olympics, in a different city', 'Shortly after the Olympics, in the same host city', 'Every 8 years', 'Only alongside Winter Olympics'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'The Commonwealth Games feature athletes primarily from?', options: ['European Union nations', 'Commonwealth nations', 'Asian nations', 'NATO member states'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'In cricket, "LBW" stands for?', options: ['Long Ball Wide', 'Leg Before Wicket', 'Last Batter Wins', 'Line Ball Warning'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'A "googly" in cricket is a type of?', options: ['Deceptive spin bowling delivery', 'Fielding position', 'Batting stance', 'Protective helmet'], correct_option: 0 },
  { category: 'sports', difficulty: 'medium', question: 'In tennis, a set won 6-0 is informally nicknamed a?', options: ['"Whitewash"', '"Bagel"', '"Blank"', '"Zero-set"'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'Tennis is played on three main surfaces: grass, clay, and?', options: ['Hard court', 'Sand', 'Synthetic turf', 'Concrete'], correct_option: 0 },
  { category: 'sports', difficulty: 'easy', question: 'The French Open tennis Grand Slam is played on which surface?', options: ['Grass', 'Hard court', 'Clay', 'Synthetic'], correct_option: 2 },
  { category: 'sports', difficulty: 'easy', question: 'The US Open tennis Grand Slam is played on which surface?', options: ['Grass', 'Clay', 'Hard court', 'Synthetic'], correct_option: 2 },
  { category: 'sports', difficulty: 'medium', question: "Wimbledon's tournament is officially known as?", options: ['The Wimbledon Masters', 'The Championships, Wimbledon', 'The All England Open', 'The Grass Slam'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: "AFL's annual award for the fairest and best player is the?", options: ['Brownlow Medal', 'Coleman Medal', 'Norm Smith Medal', 'Rising Star Award'], correct_option: 0 },
  { category: 'sports', difficulty: 'medium', question: "The NRL's equivalent best-and-fairest award is the?", options: ['Clive Churchill Medal', 'Dally M Medal', 'State Medal', 'Provan-Summons Medal'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: "Australia's premier domestic first-class cricket competition is the?", options: ['Sheffield Shield', 'Big Bash Cup', 'Domestic Ashes', 'National Cricket Trophy'], correct_option: 0 },
  { category: 'sports', difficulty: 'hard', question: 'The NBA introduced the three-point line in which decade?', options: ['1960s', '1970s', '1980s', '1990s'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Modern Olympic Games (Summer and Winter combined) are held every how many years, alternating?', options: ['1 year', '2 years', '3 years', '4 years'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'Which country traditionally leads the athletes\' parade at the Olympic opening ceremony, as the birthplace of the Games?', options: ['Italy', 'Greece', 'Egypt', 'Turkey'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: "Which nation traditionally enters last in the Olympic opening ceremony's parade of nations?", options: ['The next host nation', 'The host nation', 'The reigning champion nation', 'Greece'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'The javelin, shot put, discus and hammer throw are all part of which broader athletics category?', options: ['Track events', 'Field events', 'Combined events', 'Road events'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'Running events like the 100m, 200m and marathon are part of which broader athletics category?', options: ['Field events', 'Track events', 'Combined events', 'Indoor events'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'In athletics, the 4x100m event is an example of a?', options: ['Relay race', 'Hurdles race', 'Steeplechase', 'Pursuit race'], correct_option: 0 },
  { category: 'sports', difficulty: 'medium', question: 'In swimming, a "medley relay" involves teammates each swimming a different?', options: ['Distance', 'Stroke', 'Lane', 'Pool'], correct_option: 1 },
  { category: 'sports', difficulty: 'easy', question: 'In darts, the highest score achievable with three darts in one turn is?', options: ['170', '180', '190', '501'], correct_option: 1 },
  { category: 'sports', difficulty: 'medium', question: 'A cricket bowler who takes five wickets in a single innings is said to have taken a?', options: ['Golden over', 'Five-wicket haul ("five-for")', 'Perfect innings', 'Century of wickets'], correct_option: 1 },
];
